# Generated by Django 5.0.2 on 2024-03-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dulces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('sabor', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electronicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Categoria', models.CharField(max_length=30)),
                ('Clasificacion', models.CharField(max_length=30)),
                ('Duracion', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
